<?xml version="1.0" encoding="UTF-8"?>
<interface xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Filesystem\Exception\IOExceptionInterface" namespace="Symfony\Component\Filesystem\Exception" name="IOExceptionInterface" abstract="false" final="false" start="19" end="27">
  <file path="//var/www/html/vendor/symfony/filesystem/Exception" file="IOExceptionInterface.php" realpath="/var/www/html/vendor/symfony/filesystem/Exception/IOExceptionInterface.php" size="669" time="2022-04-01T12:33:59+00:00" unixtime="1648816439" sha1="2ef61555bbc8ad75cfbb921d441c1c859355835e" relative="ar/www/html/vendor/symfony/filesystem/Exception/IOExceptionInterface.php"/>
  <docblock>
    <description compact="IOException interface for file and input/output stream related exceptions thrown by the component."/>
    <author value="Christian GÃ¤rtner &lt;christiangaertner.film@googlemail.com&gt;"/>
  </docblock>
  <extends full="Symfony\Component\Filesystem\Exception\ExceptionInterface" namespace="Symfony\Component\Filesystem\Exception" name="ExceptionInterface"/>
  <method name="getPath" start="26" end="26" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Returns the associated path for the exception."/>
      <return type="object">
        <type full="Symfony\Component\Filesystem\Exception\string|null" namespace="Symfony\Component\Filesystem\Exception" name="string|null"/>
      </return>
    </docblock>
  </method>
  <implementors>
    <class full="Symfony\Component\Filesystem\Exception\IOException" namespace="Symfony\Component\Filesystem\Exception" name="IOException"/>
    <class full="Symfony\Component\Filesystem\Exception\FileNotFoundException" namespace="Symfony\Component\Filesystem\Exception" name="FileNotFoundException"/>
  </implementors>
  <parent full="Symfony\Component\Filesystem\Exception\ExceptionInterface" namespace="Symfony\Component\Filesystem\Exception" name="ExceptionInterface">
    <extends full="Throwable" namespace="" name="Throwable"/>
  </parent>
  <parent full="Throwable" namespace="" name="Throwable">
    <method name="getMessage" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the message"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getCode" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the exception code"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getFile" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the file in which the exception was created"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getLine" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the line on which the object was instantiated"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getTrace" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace"/>
      <return type="array"/>
    </docblock>
  </method>
    <method name="getTraceAsString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace as a string"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getPrevious" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Returns the previous Throwable"/>
      <return type="Throwable"/>
    </docblock>
  </method>
    <method name="__toString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets a string representation of the thrown object"/>
      <return type="string"/>
    </docblock>
  </method>
  </parent>
</interface>
