<?xml version="1.0" encoding="UTF-8"?>
<interface xmlns="http://xml.phpdox.net/src" full="Symfony\Component\HttpClient\Response\StreamableInterface" namespace="Symfony\Component\HttpClient\Response" name="StreamableInterface" abstract="false" final="false" start="22" end="35">
  <file path="//var/www/html/vendor/symfony/http-client/Response" file="StreamableInterface.php" realpath="/var/www/html/vendor/symfony/http-client/Response/StreamableInterface.php" size="1156" time="2022-04-12T16:02:29+00:00" unixtime="1649779349" sha1="edcfa3cd5e6c7f6d784b1e1eb31f6d4eef3c34e7" relative="ar/www/html/vendor/symfony/http-client/Response/StreamableInterface.php"/>
  <docblock>
    <description/>
    <author value="Nicolas Grekas &lt;p@tchwork.com&gt;"/>
  </docblock>
  <method name="toStream" start="34" end="34" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Casts the response to a PHP stream resource."/>
      <return type="resource"/>
      <throws description="When a network error occurs" type="object">
        <type full="Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="TransportExceptionInterface"/>
      </throws>
      <throws description="On a 3xx when $throw is true and the &quot;max_redirects&quot; option has been reached" type="object">
        <type full="Symfony\Contracts\HttpClient\Exception\RedirectionExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="RedirectionExceptionInterface"/>
      </throws>
      <throws description="On a 4xx when $throw is true" type="object">
        <type full="Symfony\Contracts\HttpClient\Exception\ClientExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="ClientExceptionInterface"/>
      </throws>
      <throws description="On a 5xx when $throw is true" type="object">
        <type full="Symfony\Contracts\HttpClient\Exception\ServerExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="ServerExceptionInterface"/>
      </throws>
    </docblock>
    <parameter name="throw" byreference="false" type="boolean" default="true"/>
  </method>
  <implementors>
    <class full="Symfony\Component\HttpClient\Response\TraceableResponse" namespace="Symfony\Component\HttpClient\Response" name="TraceableResponse"/>
    <class full="Symfony\Component\HttpClient\Response\MockResponse" namespace="Symfony\Component\HttpClient\Response" name="MockResponse"/>
    <class full="Symfony\Component\HttpClient\Response\AsyncResponse" namespace="Symfony\Component\HttpClient\Response" name="AsyncResponse"/>
    <class full="Symfony\Component\HttpClient\Response\CurlResponse" namespace="Symfony\Component\HttpClient\Response" name="CurlResponse"/>
    <class full="Symfony\Component\HttpClient\Response\NativeResponse" namespace="Symfony\Component\HttpClient\Response" name="NativeResponse"/>
  </implementors>
</interface>
